Reproduc: 
  seed: 42
  benchmark: true
  deterministic: false
CompressFramwork:
  Path: data\out1.tif
  Ratio: 256
  Train:
    #batch_size: 524288 
    #batch_size: 262144
    #batch_size: 131072
    batch_size: 65536
    #epochs: 1500
    #epochs: 762
    #epochs: 381
    epochs: 190
    device: cuda
    optimizer: 
      type: Adamax
      lr: 1e-3
    lr_scheduler:
      # name: MultiStepLR
      # milestones: [20000,50000]
      # gamma: 0.2
      name: CosineAnnealingLR
      T_max: 100584  
      eta_min: 1e-6
    #weight: [2001,65535,0.01]
    weight: [0, 100, 1.0]
  Eval:
    #batch_size: 524288
    #batch_size: 262144
    #batch_size: 131072
    batch_size: 65536
    #epochs: 150
    #epochs: 75
    #epochs: 38
    epochs: 190
    #epochs: 381
    device: cuda
  Preprocess:
    normal_min: 0
    normal_max: 100
  Network:
    input: 3
    output: 1
    #level_info: [[1.0, 4, Sine, equal]]
    level_info: [[2.0, 3, Sine, equal], [1.0, 3, Sine, equal]]
    #level_info: [[4.0, 2, Sine, equal], [2.0, 2, Sine, equal],[1.0, 3, Sine, equal]]
    #level_info: [[1.0, 2, Sine, equal], [0.8, 2, Sine, equal], [1.5, 3, Sine, aoi]]
    w0: 30

Log: 
  project_name: default
  stdlog: false
  tensorboard: true